### ISSUE TITLE
Link to component docs in release notes is 404

### ISSUE THREAD

**Issue by madStitcher** [coreui/coreui-vue#35]
The link on the v3 beta release notes is broken: https://coreui.io/vue/docs/3.0/components/

**Comment by jeanpierreribeiro** [comment]
I'm waiting too

**Comment by madStitcher** [comment]
You can get to them here: [https://coreui.io/vue/docs/3.0/components/Alert.html#usage](https://coreui.io/vue/docs/3.0/components/Alert.html#usage).

**Comment by woothu** [comment]
Hi! Thank you for reporting this error!

My respond is delayed because I was thinking that something got broken during our main page being replaced, not realizing that it was an issue with the wrong link (and lack of proper redirects)

Fixed release log: https://github.com/coreui/coreui-vue/releases/tag/3.0.0-alpha.4
