### ISSUE TITLE
Question: How can one import only needed components?

### ISSUE THREAD

**Issue by fancydev18** [coreui/coreui-vue#41]
Hi,

How can one import only needed components from CoreUI and have just those in the final build?

I tried this, but it doesn't work:
```
import CSidebar from '@coreui/vue/src/components/sidebar/CSidebar'
Vue.use(CSidebar)
```

Also, how to import the whole CSS if not using
``` import CoreuiVue from '@coreui/vue' ```
?

Thanks!

**Comment by woothu** [comment]
Hi!

SFC's are not plugins, you register them globally by Vue.component method:
```
import CSidebar from '@coreui/vue/src/components/sidebar/CSidebar'
Vue.component('CSidebar', CSidebar)
```

CSS are imported from  ``@coreui/coreui`` library ``@import "~@coreui/coreui/scss/coreui";
``

**Comment by fancydev18** [comment]
> I see some serious optimizations going on :)

haha, spot on, woothu! It's only because the vendors bundle got to 2mb. Crazy...

Looks like importing only used components (Sidebar & dependencies) saves us 200kb.  Thanks!

If anybody else needs this, here's how to import a directive:
```
import CEmitRootEvent from '@coreui/vue/src/directives/CEmitRootEvent'
Vue.directive('c-emit-root-event', CEmitRootEvent)
```

**Comment by fancydev18** [comment]
To be frank, some components seem really done for the sake of having a component, eg container. 
We're also using bootstrap-vue and would like to minimize the overlap.

**Comment by woothu** [comment]
That's why you don't have to use them :) It will be noticed in docs that component is only a wrapper.

Even for wrappers components could be useful:
1. You can exceed they functionality later,
2. Refactor and breaking changes of styles are much easier to introduce,
3. They are more likely to be gzipped better than raw HTML

Speaking of gzipping, what actually matters is gzipped bundle size, not bundle size. If you take this message, for example, it wouldn't really matter if you copy and paste it in code on one page (one js bundle) 1000 times. it should be only 1kB+original message size larger, not 1000 X this message size.
