### ISSUE TITLE
v-on:Click and @Click do not work CSwitch in Coreui-vue Pro

### ISSUE THREAD

**Issue by HAL0594** [coreui/coreui-vue#46]
I try to use @click , @change or v-on with a CSwitch in Coreui-Vue Pro also try click.native but nothing works. There is also a problem using .native in the rest of coreui-vue components.

**Comment by woothu** [comment]
Hi!

@click and @change events don't work because CSwitch component is not emitting such events, the
only event that is emitted by CSwitch component is "update:checked" https://coreui.io/vue/docs/components/switch.html"

I have tested @click.native in the CSwitch component and it works. How can I reproduce this bug?

Thank you for report about other components, after a short investigation it seems to me that @click.native doesn't work in Vue functional components (but normal @click event does work).

**Comment by rusicsemenov** [comment]
@change worked same with .native i use `@change.native="switcher = !switcher"` and add `watcher`

**Comment by zxwild** [comment]
Since only event is `update:checked`, it's possible to listen to it and pass `checked` value as a prop, the following code works ok.

```HTML
<CSwitch :checked="testValue" @update:checked="testValue = !testValue" />
```

**Comment by woothu** [comment]
You can also write
```
<CSwitch :checked.sync="testValue" />
```

**Comment by zxwild** [comment]
@woothu yeah, works nice, thanks!

**Comment by geri777** [comment]
Took me half an hour to find out how to bind <CSwitch> in Vue. The documentation is quite useless here:
https://coreui.io/vue/docs/components/switch.html
It even does not explain the parameters :key, v-bind and :value
