### ISSUE TITLE
[Form] (CInputRadio-) Documentation

### ISSUE THREAD

**Issue by darthf1** [coreui/coreui-vue#72]
Hi, I'm having a hard time going through the [documentation](https://coreui.io/vue/docs/components/form-components.html) regarding the form components.

Currently I'm trying to work with the `CInputRadio` component. I couldn't get them to work properly, but then I found the `name` prop. Yes, I know the prop is displayed in the example, but the prop is not documented anywhere on the page.

The `CInputRadio` component uses the `label` and `value` prop for the label and value of the respective radio button. But I would like to set a label on the form group. For me it would make more sense to use the `options` prop to set the radio's labels and values, and use the `label` prop to set the label for the entire group. But this would require a `CInputRadioGroup` component I guess.

But trying to figure out a solution for now, in the code I saw there was a `CFormGroup` component. This component is not documented anywhere on the website. I can use the `description` prop to achieve my goal, however if I wrap the `CInputRadio` with the `CFormGroup`, the `CInputRadio` disappears from the html source.

Minor: the clicks `+ Shared props and slots` are not referring to the correct anchor.

**Comment by woothu** [comment]
Hi!
Ad.1 name is not a prop, but attribute, in all components passing when attributes, they have default HTML behavior. Nonetheless, I agree that using HTML attributes should be better documented.

Ad.2 
Concerning 'label' prop, it works the same in all components for consistency - creating natural label for the element. You cannot have 'options' unless you have component that renders multiple CRadioInputs. We will consider creating such a component.

For now, you can do it like this:

```
<CRow form class="form-group">
    <CCol sm="3">
      Radio group name
    </CCol>
    <CCol sm="9" class="form-inline">
      <CInputRadio
        v-for="(option, optKey) in radioOptions"
        :key="option + optKey"
        :label="option"
        name="radioGroupName"
        :value="option"
        :checked="checkedRadioOption === option"
        @update:checked="() => checkedRadioOption = option"
      />
    </CCol>
</CRow>
```

Doesn't it look clean? ;) And we have full flexibility persisted. 

Ad.3 
CFormGroup is not documented because its internal component used to render other form components. In fact, it would be better to name this component differently...

Ad.4 
Thank you for the bug report.

**Comment by woothu** [comment]
The documentation is now updated

**Comment by woothu** [comment]
CInputRadioGroup introduced in af899f5a0f46c96aa7804f7b5711fdd59dc9d943.

Now the application would look like this:

```
<CRow form>
  <CCol>
    Label
  </CCol>
  <CCol>
    <CInputRadioGroup
      :options="[
        'option 1',
        { value: 'option 2', label: 'label', props: { description: 'description' }}
      ]"
      checked="option 1"
      custom
    />
  </CCol>
</CRow>
```
